/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_magicing_eigenndk_NDKUtils */

#ifndef _Included_com_magicing_eigenndk_NDKUtils
#define _Included_com_magicing_eigenndk_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_magicing_eigenndk_NDKUtils
 * Method:    invokeCmethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_magicing_eigenndk_NDKUtils_invokeCmethod
 (JNIEnv *env, jobject obj){

     return (*env)->NewStringUTF(env,"NDK 获取Native 字符串");

  }

#ifdef __cplusplus
}
#endif
#endif
